# Generated by Django 3.0.3 on 2020-05-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200503_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, editable=False, max_length=11),
        ),
    ]
