# Generated by Django 3.0.3 on 2020-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200504_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
