# Generated by Django 3.0.7 on 2020-08-25 23:14

import backend.fields
import backend.models
import backend.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', backend.fields.WrappedImageField(storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_poster_media_url, 'location': backend.models.get_poster_base_location}), upload_to=backend.models.get_image_location)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_local',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_status',
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_file',
            field=backend.fields.WrappedFileField(default='', storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_video_media_url, 'location': backend.models.get_video_base_location}), upload_to=backend.models.get_video_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='transcode_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('started', 'Processing'), ('finished', 'Done'), ('failed', 'Error')], db_column='video_status', default='queued', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_file',
            field=backend.fields.WrappedFileField(blank=True, default='', storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_video_media_url, 'location': backend.models.get_video_base_location}), upload_to=backend.models.get_video_location),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('draft', 'Draft')], default='PRIVATE', max_length=8),
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.ImageSet'),
        ),
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='image_set',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ImageSet'),
        ),
    ]
