# Generated by Django 3.0.7 on 2020-08-27 01:13

import backend.fields
import backend.models
import backend.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_refactor_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uploaded_file',
            field=backend.fields.WrappedFileField(blank=True, max_length=255, storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_video_media_url, 'location': backend.models.get_video_base_location}), upload_to=backend.models.get_video_location),
        ),
    ]
