# Generated by Django 3.0.7 on 2020-09-21 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('reason', models.CharField(choices=[('SP', 'Unwanted commercial content or spam'), ('PO', 'Pornography or sexually explicit material'), ('CA', 'Child abuse'), ('HV', 'Hate speech or graphic violence'), ('HB', 'Harassment or bullying')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Ticket')),
                ('body', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
            bases=('backend.ticket',),
        ),
        migrations.CreateModel(
            name='CommentTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Ticket')),
                ('body', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Channel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Comment')),
            ],
            bases=('backend.ticket',),
        ),
    ]
