# Generated by Django 3.0.7 on 2020-11-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_channel_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
