# Generated by Django 3.0.7 on 2021-03-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_change_managers_on_video'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
            ],
        ),
    ]
