# Generated by Django 3.0.7 on 2022-01-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_video_transcoded_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranscodedVideo',
        ),
    ]
