# Generated by Django 3.0.7 on 2020-07-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
