# Generated by Django 3.0.7 on 2020-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipadress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
