# Generated by Django 3.0.7 on 2020-11-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user_banned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
