# Generated by Django 3.0.7 on 2021-01-05 01:43

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_channelbackground'),
    ]

    operations = [
        TrigramExtension(),
    ]
