# Generated by Django 3.0.7 on 2021-02-28 02:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_strikes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
