# Generated by Django 3.0.7 on 2021-03-21 00:25

import backend.fields
import backend.models
import backend.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_move_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscodedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_file', backend.fields.WrappedFileField(storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_video_media_url, 'location': backend.models.get_video_base_location}), upload_to=backend.models.get_video_location)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Processing'), ('finished', 'Done'), ('failed', 'Error')], default='queued', max_length=255)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='transcoded_video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TranscodedVideo'),
        ),
    ]
