# Generated by Django 3.0.7 on 2021-03-21 00:27

from django.db import migrations

def migrate(apps, schema_editor):
    Video = apps.get_model('backend', 'Video')
    TranscodedVideo = apps.get_model('backend', 'TranscodedVideo')

    for video in Video.objects.all():
        video.transcoded_video = TranscodedVideo.objects.create(status=video.transcode_status, job_id=video.job_id, playlist_file=video.playlist_file)
        video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_create_TranscodedVideo'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
