# Generated by Django 3.0.7 on 2021-03-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcode_status',
        ),
    ]
