# Generated by Django 3.0.7 on 2021-07-31 13:50

import backend.fields
import backend.models
import backend.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_cleanup_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodedvideo',
            name='playlist_file',
            field=backend.fields.WrappedFileField(storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_video_media_url, 'location': backend.models.get_video_base_location}), upload_to=backend.models.get_playlist_location),
        ),
        migrations.CreateModel(
            name='BunnyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Processing'), ('finished', 'Done'), ('failed', 'Error')], default='queued', max_length=255)),
                ('bunny_guid', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
        ),
    ]
