# Generated by Django 3.2.11 on 2022-01-09 01:34

import backend.models
import backend.storage
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_delete_transcodedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_new',
            field=imagekit.models.fields.ProcessedImageField(null=True, default=None, storage=backend.storage.WrappedBCDNStorage(local_options={'base_url': backend.models.get_poster_media_url, 'location': backend.models.get_poster_base_location}), upload_to=backend.models.get_image_location),
            preserve_default=False,
        ),
    ]
