# Generated by Django 3.2.11 on 2022-01-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_image_thumbnail_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='thumbnail_new',
            new_name='thumbnail',
        ),
    ]
