# Generated by Django 3.2.12 on 2022-06-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_imageset_custom_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age_restricted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
