# Generated by Django 3.2.18 on 2023-06-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_video_age_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunnyvideo',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
