# Generated by Django 3.2.18 on 2023-06-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_bunnyvideo_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunnyvideo',
            name='views_gained',
            field=models.BigIntegerField(default=0),
        ),
    ]
